CREATE TABLE "GHCN_DATA"."GHCN_TMIN" () INHERITS("GHCN_DATA"."GHCN_BASE")
WITH (
  OIDS=FALSE
);
ALTER TABLE "GHCN_DATA"."GHCN_TMIN"
  OWNER TO postgres;
ALTER TABLE "GHCN_DATA"."GHCN_TMIN"
  ADD CONSTRAINT "GHCN_TMIN_PRIMARY_KEY" PRIMARY KEY("ID","YEAR","MONTH","DAY")
