CREATE TABLE "GHCN_DATA"."GHCN_TAVG" () INHERITS("GHCN_DATA"."GHCN_BASE")
WITH (
  OIDS=FALSE
);
ALTER TABLE "GHCN_DATA"."GHCN_TAVG"
  OWNER TO postgres;
ALTER TABLE "GHCN_DATA"."GHCN_TAVG"
  ADD CONSTRAINT "GHCN_TAVG_PRIMARY_KEY" PRIMARY KEY("ID","YEAR","MONTH","DAY")
