CREATE TABLE "GHCN_DATA"."GHCN_AWDR"
() INHERITS ("GHCN_DATA"."GHCN_BASE")
WITH (
  OIDS=FALSE
);
ALTER TABLE "GHCN_DATA"."GHCN_AWDR"
  OWNER TO postgres;
ALTER TABLE "GHCN_DATA"."GHCN_AWDR"
  ADD CONSTRAINT "GHCN_AWDR_PRIMARY_KEY" PRIMARY KEY("ID","YEAR","MONTH","DAY")
