CREATE TABLE "GHCN_DATA"."GHCN_SNOW" () INHERITS("GHCN_DATA"."GHCN_BASE")
WITH (
  OIDS=FALSE
);
ALTER TABLE "GHCN_DATA"."GHCN_SNOW"
  OWNER TO postgres;
ALTER TABLE "GHCN_DATA"."GHCN_SNOW"
  ADD CONSTRAINT "GHCN_SNOW_PRIMARY_KEY" PRIMARY KEY("ID","YEAR","MONTH","DAY")
