CREATE TABLE "GHCN_DATA"."GHCN_WT" () INHERITS("GHCN_DATA"."GHCN_BASE")
WITH (
  OIDS=FALSE
);
ALTER TABLE "GHCN_DATA"."GHCN_WT"
  OWNER TO postgres;
ALTER TABLE "GHCN_DATA"."GHCN_WT"
  ADD CONSTRAINT "GHCN_WT_PRIMARY_KEY" PRIMARY KEY("ID","YEAR","MONTH","DAY","ELEMENT")
