CREATE TABLE "GHCN_DATA"."GHCN_TMAX" () INHERITS("GHCN_DATA"."GHCN_BASE")
WITH (
  OIDS=FALSE
);
ALTER TABLE "GHCN_DATA"."GHCN_TMAX"
  OWNER TO postgres;
ALTER TABLE "GHCN_DATA"."GHCN_TMAX"
  ADD CONSTRAINT "GHCN_TMAX_PRIMARY_KEY" PRIMARY KEY("ID","YEAR","MONTH","DAY")
