CREATE TABLE "GHCN_DATA"."GHCN_TOBS" () INHERITS("GHCN_DATA"."GHCN_BASE")
WITH (
  OIDS=FALSE
);
ALTER TABLE "GHCN_DATA"."GHCN_TOBS"
  OWNER TO postgres;
ALTER TABLE "GHCN_DATA"."GHCN_TOBS"
  ADD CONSTRAINT "GHCN_TOBS_PRIMARY_KEY" PRIMARY KEY("ID","YEAR","MONTH","DAY")
