CREATE TABLE "GHCN_DATA"."GHCN_SNWD" () INHERITS("GHCN_DATA"."GHCN_BASE")
WITH (
  OIDS=FALSE
);
ALTER TABLE "GHCN_DATA"."GHCN_SNWD"
  OWNER TO postgres;
ALTER TABLE "GHCN_DATA"."GHCN_SNWD"
  ADD CONSTRAINT "GHCN_SNWD_PRIMARY_KEY" PRIMARY KEY("ID","YEAR","MONTH","DAY")
