CREATE TABLE "GHCN_DATA"."GHCN_PRCP" () INHERITS("GHCN_DATA"."GHCN_BASE")
WITH (
  OIDS=FALSE
);
ALTER TABLE "GHCN_DATA"."GHCN_PRCP"
  OWNER TO postgres;
ALTER TABLE "GHCN_DATA"."GHCN_PRCP"
  ADD CONSTRAINT "GHCN_PRCP_PRIMARY_KEY" PRIMARY KEY("ID","YEAR","MONTH","DAY")
