ALTER TABLE "GHCN_DATA"."GHCN_GRANULAR_PRIMARY_KEY" ADD PRIMARY KEY ("ID", "YEAR", "MONTH", "DAY", "ELEMENT", "VALUE");
ALTER TABLE "META"."COUNTRY_PRIMARY_KEY" ADD PRIMARY KEY ("CODE", "NAME");
ALTER TABLE "META"."INVENTORY_PRIMARY_KEY" ADD PRIMARY KEY ("ID","ELEMENT");
ALTER TABLE "META"."STATES_PRIMARY_KEY" ADD PRIMARY KEY ("CODE", "NAME");
ALTER TABLE "META"."STATIONS_PRIMARY_KEY" ADD PRIMARY KEY ("ID");